#!/usr/bin/env ruby

require './lib/peg/scanner'
require './lib/peg/parser'
#require './lib/peg/code_generator'

tokens = Peg::Scanner.scan(STDIN.read)
puts tokens.inspect
ast = Peg::Parser.new.parse(tokens)
#puts ast
